// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Rwntk2fHscu4yFoIcTD6zoXM96k8mS4',
    appId: '1:460314560335:web:23970937c3b6668c76e73a',
    messagingSenderId: '460314560335',
    projectId: 'fir-app-d2c42',
    authDomain: 'fir-app-d2c42.firebaseapp.com',
    storageBucket: 'fir-app-d2c42.appspot.com',
    measurementId: 'G-RM20JLXZX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQt-fOZoTY7DeAmK1R7GQ6CXly4sUrY0',
    appId: '1:460314560335:android:c203afa6cd9ff08b76e73a',
    messagingSenderId: '460314560335',
    projectId: 'fir-app-d2c42',
    storageBucket: 'fir-app-d2c42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTk0KYiM8kTK7gn7eTnnw6ltNsENTZgm8',
    appId: '1:460314560335:ios:295993690836dce076e73a',
    messagingSenderId: '460314560335',
    projectId: 'fir-app-d2c42',
    storageBucket: 'fir-app-d2c42.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTk0KYiM8kTK7gn7eTnnw6ltNsENTZgm8',
    appId: '1:460314560335:ios:02dac599a23deb8d76e73a',
    messagingSenderId: '460314560335',
    projectId: 'fir-app-d2c42',
    storageBucket: 'fir-app-d2c42.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
